### ISSUE TITLE
播放视频或者图片之后，执行onDestroy，再次进入app奔溃

### ISSUE THREAD

**Issue by Alexxiaopang** [ykbjson/simpledlna#2]
播放视频或者图片之后，执行onDestroy，再次进入app奔溃
使用你的demo也一样，请问这个怎么解决

**Comment by javaertj** [comment]
有具体的报错信息吗，我目前没遇到过

**Comment by CangJieStore** [comment]
@ykbjson 有个问题请教下，国内哪家的电视支持图片投屏？

**Comment by zhaoyongjiang** [comment]
> 播放视频或者图片之后，执行onDestroy，再次进入app奔溃
> 使用你的demo也一样，请问这个怎么解决

请问这个问题怎么解决

**Comment by zhaoyongjiang** [comment]
> 

time: 2022-11-25 11:11:57
java.lang.NullPointerException: Attempt to invoke interface method 'void org.fourthline.cling.registry.RegistryListener.remoteDeviceUpdated(org.fourthline.cling.registry.Registry, org.fourthline.cling.model.meta.RemoteDevice)' on a null object reference
	at org.fourthline.cling.registry.RemoteItems$2.run(RemoteItems.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

duration: 14m 4s
versionCode: 980
versionName: 9.8.0 Debug
androidSDK: Android 30
androidVersion: 11
rom: vivo
cpuABI: arm64-v8a
phoneName: V2133A
locale: zh

**Comment by Crazydear** [comment]
我也遇到了同样的问题,把destroy去掉不会崩溃,但是又出现了搜索不到设备的问题
