### ISSUE TITLE
播放本地视频

### ISSUE THREAD

**Issue by zjsmy** [ykbjson/simpledlna#4]
播放本地视频报错
2022-04-14 16:47:36.040 13335-13629/com.ykbjson.app.simpledlna E/org.protocols.http.NanoHTTPD: Could not send response to the client
2022-04-14 16:47:36.041 13335-13629/com.ykbjson.app.simpledlna E/org.protocols.http.NanoHTTPD: java.io.IOException: Stream Closed
        at java.io.FileInputStream.read(FileInputStream.java:306)
        at org.protocols.http.response.Response.sendBody(Response.java:350)
        at org.protocols.http.response.Response.sendBodyWithCorrectEncoding(Response.java:327)
        at org.protocols.http.response.Response.sendBodyWithCorrectTransferAndEncoding(Response.java:308)
        at org.protocols.http.response.Response.send(Response.java:268)
        at org.protocols.http.HTTPSession.execute(HTTPSession.java:435)
        at org.protocols.http.ClientHandler.run(ClientHandler.java:75)

**Comment by javaertj** [comment]
我最近也遇到了，在切换投屏类型的时候就出现socket流关闭的异常，我用kodi当接收端就会遇到，但是投屏家里的暴风、创维、康佳电视就没问题，可能是cling对新的dlna协议支持不够友好，导致的问题。正在排查中。
